#Use new images to yield newer compilers and packages
sudo: required
language: cpp

matrix:
  include:
    - compiler: g++
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-4.9
            - lcov
            - gcov
      env: COMPILER=g++-4.9
    - compiler: clang
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - cmake
            - cmake-data
            - clang-3.7
      env: COMPILER=clang++-3.7

script:
  - cmake --version
  - ./script/run-tests.sh

