#Use new images to yield newer compilers and packages
sudo: required
dist: precise
language: cpp

#Sorry no visual studio available in travis...
matrix:
    include:
        - compiler: gcc
            addons:
                apt:
                    sources:
                        #add PPAs with more up-to-date toolchains
                        - ubuntu-toolchain-r-test
                    packages:
                        # install toolchains
                        - g++-5
            env: COMPILER=g++-5
        - compiler: clang
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-precise-3.6
                    packages:
                        - clang-3.6
            env: COMPILER=clang++-3.6
before_install:
    - pip install --user cpp-coveralls
script: 
    - ./script/run-tests.sh
after_install:
    - coveralls --exclude app --exclude scripts --gcov-options '\-lp'

