language: cpp
#Sorry no visual studio available in travis...
compiler:
    - gcc
    - clang
before_install:
    - pip install --user cpp-coveralls
script: 
    - ./script/run-tests.sh
after_install:
    - coveralls --exclude app --exclude scripts --exclude tests --gcov-options '\-lp'

