#Use new images to yield newer compilers and packages
sudo: required
dist: precise
language: cpp
os: linux
compiler: gcc

#addons:
    #apt:
        #sources:
            ##add PPAs with more up-to-date toolchains
            #- ubuntu-toolchain-r-test
        #packages:
            ## install toolchains
            #- g++-5

#Sorry no visual studio available in travis...
#matrix:
    #include:
        #- compiler: gcc
script:
    - ./script/run-tests.sh

